<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeathSystemAndCauseSeeder extends Seeder
{
    public function run(): void
    {
        $systems = [
            1 => 'CIRCULATORIO',
            2 => 'DESCONOCIDO',
            3 => 'DIGESTIVO',
            4 => 'HEMATOPOYÉTICO',
            5 => 'INMUNOLOGICO',
            6 => 'LOCOMOTOR',
            7 => 'MULTISISTEMICO',
            8 => 'MULTISISTÉMICO',
            9 => 'MUSCULAR',
            10 => 'MUSCULOESQUELETICO',
            11 => 'MUSCULOESQUELÉTICO',
            12 => 'NERVIOSO',
            13 => 'REPRODUCTOR',
            14 => 'RESPIRATORIO',
            15 => 'RESPIRATORIO / CIRCULATORIO',
            16 => 'TEGUMENTARIO',
            17 => 'URINARIO',
        ];

        foreach ($systems as $id => $name) {
            DB::table('death_systems')->insert([
                'id' => $id,
                'name' => $name,
            ]);
        }

        $causes = [
            ['id' => 1, 'name' => 'ABORTO', 'death_system_id' => 13],
            ['id' => 2, 'name' => 'ABSCESO', 'death_system_id' => 11],
            ['id' => 3, 'name' => 'ANEMIA', 'death_system_id' => 4],
            ['id' => 4, 'name' => 'ARTERIAL', 'death_system_id' => 1],
            ['id' => 5, 'name' => 'ARTICULAR', 'death_system_id' => 6],
            ['id' => 6, 'name' => 'ARTRITIS', 'death_system_id' => 6],
            ['id' => 7, 'name' => 'ASFIXIA MECÁNICA', 'death_system_id' => 14],
            ['id' => 8, 'name' => 'ASFIXIA POR CINTURÓN AL CUELLO', 'death_system_id' => 14],
            ['id' => 9, 'name' => 'ASFIXIA POR EDEMA DE CUELLO', 'death_system_id' => 14],
            ['id' => 10, 'name' => 'ASTENIA EN DECÚBITO', 'death_system_id' => 11],
            ['id' => 11, 'name' => 'BAJA CONDICIÓN', 'death_system_id' => 11],
            ['id' => 12, 'name' => 'BAJO DESARROLLO', 'death_system_id' => 11],
            ['id' => 13, 'name' => 'BRUCELOSIS', 'death_system_id' => 8],
            ['id' => 14, 'name' => 'CAQUEXIA', 'death_system_id' => 8],
            ['id' => 15, 'name' => 'CARDIOPATÍA', 'death_system_id' => 1],
            ['id' => 16, 'name' => 'CARDIORRESPECT', 'death_system_id' => 1],
            ['id' => 17, 'name' => 'CAUDOFAGIA', 'death_system_id' => 7],
            ['id' => 18, 'name' => 'CESAREA', 'death_system_id' => 13],
            ['id' => 19, 'name' => 'CIRROSIS HEPATICA', 'death_system_id' => 3],
            ['id' => 20, 'name' => 'CISTITIS', 'death_system_id' => 17],
            ['id' => 21, 'name' => 'COLAGO CARDIO RESPIRATORIO', 'death_system_id' => 14],
            ['id' => 22, 'name' => 'COLAPSO CARDIO RESPITARIO', 'death_system_id' => 14],
            ['id' => 23, 'name' => 'COLAPSO CIRCULATORIO AGUDO', 'death_system_id' => 1],
            ['id' => 24, 'name' => 'COMP. CON CIRCOVIRUS', 'death_system_id' => 16],
            ['id' => 25, 'name' => 'COMP. CON SALMONELLA', 'death_system_id' => 3],
            ['id' => 26, 'name' => 'COMP. E COLI', 'death_system_id' => 3],
            ['id' => 27, 'name' => 'COMPLEJO RESPIRATORIO', 'death_system_id' => 14],
            ['id' => 28, 'name' => 'COMPLICACIÓN POST-OPERATORIA', 'death_system_id' => 8],
            ['id' => 29, 'name' => 'CONDICIÓN CORPORAL', 'death_system_id' => 9],
            ['id' => 30, 'name' => 'CONGESTIÓN', 'death_system_id' => 14],
            ['id' => 31, 'name' => 'DEBILIDAD', 'death_system_id' => 6],
            ['id' => 32, 'name' => 'DESCOMPUESTA', 'death_system_id' => 2],
            ['id' => 33, 'name' => 'DESNUTRICIÓN', 'death_system_id' => 3],
            ['id' => 34, 'name' => 'DISFAGIA', 'death_system_id' => 11],
            ['id' => 35, 'name' => 'EDEMA DE PULMÓN', 'death_system_id' => 15],
            ['id' => 36, 'name' => 'EMACIACION', 'death_system_id' => 10],
            ['id' => 37, 'name' => 'ENCEFALITIS VIRAL/BACTERIANA', 'death_system_id' => 12],
            ['id' => 38, 'name' => 'ENDOCARDITIS FIBRINOSA', 'death_system_id' => 1],
            ['id' => 39, 'name' => 'ENDOCARDITIS VALVULAR', 'death_system_id' => 1],
            ['id' => 40, 'name' => 'ENDOCARDITIS VEGETATIVA', 'death_system_id' => 1],
            ['id' => 41, 'name' => 'ENDOMETRITIS', 'death_system_id' => 13],
            ['id' => 42, 'name' => 'ENFERMEDAD', 'death_system_id' => 8],
            ['id' => 43, 'name' => 'ENTERITIS', 'death_system_id' => 3],
            ['id' => 44, 'name' => 'ENTERITIS GASEOSA', 'death_system_id' => 3],
            ['id' => 45, 'name' => 'ENTERITIS HEMORRAGICA', 'death_system_id' => 3],
            ['id' => 46, 'name' => 'ENTERITIS INFLAMACIÓN ULCERONOSA', 'death_system_id' => 3],
            ['id' => 47, 'name' => 'ENTERITIS PARALÍTICA', 'death_system_id' => 3],
            ['id' => 48, 'name' => 'ENTEROCOLITIS', 'death_system_id' => 3],
            ['id' => 50, 'name' => 'ENTERONEUMONÍA', 'death_system_id' => 3],
            ['id' => 51, 'name' => 'EPILEPSIA', 'death_system_id' => 12],
            ['id' => 52, 'name' => 'ESTRANGULAMIENTO', 'death_system_id' => 7],
            ['id' => 53, 'name' => 'ESPLENOMEGALIA', 'death_system_id' => 7],
            ['id' => 54, 'name' => 'FALLA HEPATICA', 'death_system_id' => 3],
            ['id' => 55, 'name' => 'FALLA MULTISISTÉMICA', 'death_system_id' => 8],
            ['id' => 56, 'name' => 'FALLA RENAL', 'death_system_id' => 17],
            ['id' => 57, 'name' => 'FALLA RESPIRATORIA', 'death_system_id' => 14],
            ['id' => 58, 'name' => 'FALLO CARDIACO', 'death_system_id' => 1],
            ['id' => 59, 'name' => 'FALLO CARDIORESPIRATORIO', 'death_system_id' => 1],
            ['id' => 60, 'name' => 'FALLO CIRCULATORIO', 'death_system_id' => 1],
            ['id' => 61, 'name' => 'FIEBRE', 'death_system_id' => 8],
            ['id' => 62, 'name' => 'FRACTURA DE FÉMUR', 'death_system_id' => 6],
            ['id' => 63, 'name' => 'FRACTURA DE MIEMBRO', 'death_system_id' => 6],
            ['id' => 64, 'name' => 'FRACTURA ESCAPULAR', 'death_system_id' => 6],
            ['id' => 65, 'name' => 'FRACTURA DEL HUESO FEMORAL', 'death_system_id' => 6],
            ['id' => 66, 'name' => 'FRACTURA EN CUERPO VERTEBRAL', 'death_system_id' => 6],
            ['id' => 67, 'name' => 'FRACTURA MÚLTIPLE', 'death_system_id' => 6],
            ['id' => 68, 'name' => 'GASTRITIS HEMORRAGICA', 'death_system_id' => 3],
            ['id' => 69, 'name' => 'GASTROENTERITIS HEMORRÁGICA', 'death_system_id' => 3],
            ['id' => 70, 'name' => 'HECES ALQUITRAN', 'death_system_id' => 3],
            ['id' => 71, 'name' => 'HEMOPERITONEO', 'death_system_id' => 1],
            ['id' => 72, 'name' => 'HEMORRAGIA', 'death_system_id' => 7],
            ['id' => 73, 'name' => 'HEMORRAGIA ESPLÉNICA', 'death_system_id' => 4],
            ['id' => 74, 'name' => 'HEMORRAGIA HEPÁTICA', 'death_system_id' => 3],
            ['id' => 75, 'name' => 'HEMORRAGIA INTERNA', 'death_system_id' => 7],
            ['id' => 76, 'name' => 'HEMORRAGIA INTESTINAL', 'death_system_id' => 3],
            ['id' => 77, 'name' => 'HEMORRAGIA POR PARTO/ABORTO', 'death_system_id' => 13],
            ['id' => 78, 'name' => 'HEMORRAGIA RUPTURA HEPATICA', 'death_system_id' => 3],
            ['id' => 79, 'name' => 'HEMORRAGIA RUPTURA HEPÁTICA', 'death_system_id' => 3],
            ['id' => 80, 'name' => 'HEMORRAGIA RUPTURA UTERINA', 'death_system_id' => 13],
            ['id' => 81, 'name' => 'HEMORRAGIA UTERINA', 'death_system_id' => 13],
            ['id' => 82, 'name' => 'HEMORRAGIA VAGINAL', 'death_system_id' => 13],
            ['id' => 83, 'name' => 'HEMORRAGIA VULVAR', 'death_system_id' => 13],
            ['id' => 84, 'name' => 'HEMORRAGIAS MÚLTIPLES', 'death_system_id' => 1],
            ['id' => 85, 'name' => 'HEPATITIS', 'death_system_id' => 3],
            ['id' => 86, 'name' => 'HEPATITIS CRONICA', 'death_system_id' => 3],
            ['id' => 87, 'name' => 'HEPATOBILIAN', 'death_system_id' => 3],
            ['id' => 88, 'name' => 'HEPATOMEGALIA', 'death_system_id' => 3],
            ['id' => 89, 'name' => 'HEPATOSIS', 'death_system_id' => 3],
            ['id' => 90, 'name' => 'HERNIA', 'death_system_id' => 3],
            ['id' => 91, 'name' => 'HERNIA DIAFRAGMÁTICA', 'death_system_id' => 11],
            ['id' => 92, 'name' => 'HERNIA ESCROTAL', 'death_system_id' => 10],
            ['id' => 93, 'name' => 'HERNIA UMBILICAL', 'death_system_id' => 3],
            ['id' => 94, 'name' => 'HIDROCÉFALO', 'death_system_id' => 12],
            ['id' => 95, 'name' => 'HIDRONEFROSIS', 'death_system_id' => 17],
            ['id' => 96, 'name' => 'HISTEROTOMÍA', 'death_system_id' => 13],
            ['id' => 97, 'name' => 'INANICIÓN', 'death_system_id' => 3],
            ['id' => 98, 'name' => 'INCAPACIDAD DEL TREN POSTERIOR', 'death_system_id' => 6],
            ['id' => 99, 'name' => 'INDIGESTIÓN', 'death_system_id' => 3],
            ['id' => 100, 'name' => 'INFARTO', 'death_system_id' => 1],
            ['id' => 101, 'name' => 'INFARTO AL MIOCARDIO', 'death_system_id' => 1],
            ['id' => 102, 'name' => 'INFLAMACIÓN ARTICULAR', 'death_system_id' => 6],
            ['id' => 103, 'name' => 'INFLAMACIÓN MUSCULAR', 'death_system_id' => 6],
            ['id' => 104, 'name' => 'INFLUENZA AVIAR', 'death_system_id' => 14],
            ['id' => 105, 'name' => 'INMUNOSUPRESION', 'death_system_id' => 5],
            ['id' => 106, 'name' => 'INSUFICIENCIA CARDIO-RESPIRATORIO', 'death_system_id' => 1],
            ['id' => 107, 'name' => 'INSUFICIENCIA RENAL', 'death_system_id' => 17],
            ['id' => 108, 'name' => 'LESIONES COMP. CON CIRCOVIRUS', 'death_system_id' => 8],
            ['id' => 109, 'name' => 'LESIONES COMP. CON E COLI', 'death_system_id' => 3],
            ['id' => 110, 'name' => 'LESIONES COMP. CON POLISEROSITIS', 'death_system_id' => 14],
            ['id' => 111, 'name' => 'LESIONES COMP. CON SALMONELLA', 'death_system_id' => 3],
            ['id' => 112, 'name' => 'LESIONES COMP. CON VIRUS DE MAREK', 'death_system_id' => 8],
            ['id' => 113, 'name' => 'LUXACIÓN DE ARTICULACIÓN DEL FÉMUR', 'death_system_id' => 6],
            ['id' => 114, 'name' => 'LUXACION DE LA CABEZA DEL FEMUR', 'death_system_id' => 6],
            ['id' => 115, 'name' => 'MAL DE MONTAÑA', 'death_system_id' => 1],
            ['id' => 116, 'name' => 'MALA CONDICION', 'death_system_id' => 9],
            ['id' => 117, 'name' => 'MASTITIS', 'death_system_id' => 13],
            ['id' => 118, 'name' => 'MENINGITIS', 'death_system_id' => 12],
            ['id' => 119, 'name' => 'METRITIS', 'death_system_id' => 13],
            ['id' => 120, 'name' => 'MORTINATO', 'death_system_id' => 13],
            ['id' => 121, 'name' => 'METRITIS CRÓNICA', 'death_system_id' => 13],
            ['id' => 122, 'name' => 'MIOCARDIOPATÍA', 'death_system_id' => 1],
            ['id' => 123, 'name' => 'MIOCARDITIS', 'death_system_id' => 1],
            ['id' => 124, 'name' => 'MUERTE EN CAMA', 'death_system_id' => 2],
            ['id' => 125, 'name' => 'MUERTE EN TRASLADO', 'death_system_id' => 2],
            ['id' => 126, 'name' => 'MUERTE SÚBITA', 'death_system_id' => 2],
            ['id' => 127, 'name' => 'NEFRITIS', 'death_system_id' => 17],
            ['id' => 128, 'name' => 'NEFROSIS', 'death_system_id' => 17],
            ['id' => 129, 'name' => 'NEOPLASIA', 'death_system_id' => 8],
            ['id' => 130, 'name' => 'NEOPLASIA ESPLENICA', 'death_system_id' => 3],
            ['id' => 131, 'name' => 'NEOPLASIA PÁNCREAS', 'death_system_id' => 3],
            ['id' => 132, 'name' => 'NEUMONÍA', 'death_system_id' => 14],
            ['id' => 133, 'name' => 'NEUMONIA ABSCEDATIVA', 'death_system_id' => 14],
            ['id' => 134, 'name' => 'NEUMONÍA EXUDATIVA', 'death_system_id' => 14],
            ['id' => 135, 'name' => 'NEUMONÍA INTERSTICIAL', 'death_system_id' => 14],
            ['id' => 136, 'name' => 'PANCREATITIS', 'death_system_id' => 3],
            ['id' => 137, 'name' => 'PARÁLISIS', 'death_system_id' => 6],
            ['id' => 138, 'name' => 'PARO CARDIACO', 'death_system_id' => 1],
            ['id' => 139, 'name' => 'PERICARDITIS', 'death_system_id' => 1],
            ['id' => 140, 'name' => 'PERICARDITIS FIBRINOSA', 'death_system_id' => 1],
            ['id' => 141, 'name' => 'PERITONITIS', 'death_system_id' => 3],
            ['id' => 142, 'name' => 'PIEDRA', 'death_system_id' => 17],
            ['id' => 143, 'name' => 'PIELONEFRITIS', 'death_system_id' => 17],
            ['id' => 144, 'name' => 'PIOMETRA', 'death_system_id' => 13],
            ['id' => 145, 'name' => 'PLEURONEUMONÍA', 'death_system_id' => 14],
            ['id' => 146, 'name' => 'PODODERMATITIS', 'death_system_id' => 6],
            ['id' => 147, 'name' => 'POLIARTRITIS', 'death_system_id' => 6],
            ['id' => 148, 'name' => 'POLISEROSITIS', 'death_system_id' => 3],
            ['id' => 149, 'name' => 'POSIBLE FRACTURA', 'death_system_id' => 6],
            ['id' => 150, 'name' => 'POSTACIÓN CARDÍACA', 'death_system_id' => 1],
            ['id' => 151, 'name' => 'POSTRADA(O)', 'death_system_id' => 6],
            ['id' => 152, 'name' => 'PROBLEMA NERVIOSO', 'death_system_id' => 12],
            ['id' => 153, 'name' => 'PROBLEMAS DE LOCOMOCIÓN', 'death_system_id' => 6],
            ['id' => 154, 'name' => 'PROBLEMAS NERVIOSOS', 'death_system_id' => 12],
            ['id' => 155, 'name' => 'PROBLEMAS PODALES', 'death_system_id' => 6],
            ['id' => 156, 'name' => 'PROLAPSO', 'death_system_id' => 13],
            ['id' => 157, 'name' => 'PROLAPSO RECTAL', 'death_system_id' => 17],
            ['id' => 158, 'name' => 'PROLAPSO UTERINO', 'death_system_id' => 13],
            ['id' => 159, 'name' => 'PROLAPSO VAGINAL', 'death_system_id' => 13],
            ['id' => 160, 'name' => 'PROLAPSO VESICAL', 'death_system_id' => 13],
            ['id' => 161, 'name' => 'RETENCIÓN', 'death_system_id' => 13],
            ['id' => 162, 'name' => 'RETENCIÓN UTERINA', 'death_system_id' => 13],
            ['id' => 163, 'name' => 'RICKETS', 'death_system_id' => 11],
            ['id' => 164, 'name' => 'RUPTURA DE LA AORTA', 'death_system_id' => 1],
            ['id' => 165, 'name' => 'RUPTURA DE VEJIGA', 'death_system_id' => 17],
            ['id' => 166, 'name' => 'RUPTURA ESPLÉNICA', 'death_system_id' => 4],
            ['id' => 167, 'name' => 'RUPTURA GASTRICA', 'death_system_id' => 3],
            ['id' => 168, 'name' => 'RUPTURA GASTROINTESTINAL', 'death_system_id' => 3],
            ['id' => 169, 'name' => 'RUPTURA HEPÁTICA', 'death_system_id' => 3],
            ['id' => 170, 'name' => 'S.P.A', 'death_system_id' => 13],
            ['id' => 171, 'name' => 'SALMONELLA', 'death_system_id' => 3],
            ['id' => 172, 'name' => 'SALPINGITIS', 'death_system_id' => 13],
            ['id' => 173, 'name' => 'SEPTICEMIA', 'death_system_id' => 8],
            ['id' => 174, 'name' => 'SHOCK', 'death_system_id' => 8],
            ['id' => 175, 'name' => 'SHOCK SEPTICO', 'death_system_id' => 8],
            ['id' => 176, 'name' => 'SÍNDROME NEFRÓTICO', 'death_system_id' => 17],
            ['id' => 177, 'name' => 'SINTOMAS NERVIOSO', 'death_system_id' => 12],
            ['id' => 178, 'name' => 'TORSION GASTRICA', 'death_system_id' => 3],
            ['id' => 179, 'name' => 'TORSIÓN GASTROINTESTINAL', 'death_system_id' => 3],
            ['id' => 180, 'name' => 'TORSIÓN INTESTINAL', 'death_system_id' => 3],
            ['id' => 181, 'name' => 'TRAUMATISMO', 'death_system_id' => 8],
            ['id' => 182, 'name' => 'TUMOR', 'death_system_id' => 8],
            ['id' => 183, 'name' => 'UBRE DESPREDIDA', 'death_system_id' => 3],
            ['id' => 184, 'name' => 'ULCERA CATARRAL', 'death_system_id' => 3],
            ['id' => 185, 'name' => 'ULCERA GÁSTRICA', 'death_system_id' => 3],
            ['id' => 186, 'name' => 'ULCERA HEMORRAGICA', 'death_system_id' => 3],
            ['id' => 187, 'name' => 'ULCERA INTESTINAL', 'death_system_id' => 3],
            ['id' => 188, 'name' => 'UROLITIASIS', 'death_system_id' => 17],
            ['id' => 189, 'name' => 'VÓMITO', 'death_system_id' => 3],
            ['id' => 193, 'name' => 'SACRIFICADA POSTRADA', 'death_system_id' => 6],
            ['id' => 194, 'name' => 'SACRIFICADA PODALES', 'death_system_id' => 6],
            ['id' => 195, 'name' => 'HISTERECTOMÍA', 'death_system_id' => 13],
        ];

        foreach ($causes as $cause) {
            DB::table('death_causes')->insert([
                'id' => $cause['id'],
                'name' => $cause['name'],
                'death_system_id' => $cause['death_system_id'],
            ]);
        }
    }
}
